
name: Publish Docker image

on:
  push:
    branches:
      - main
      - releases/** # From a cool demo.
  release:
    types: [published]

jobs:
  push_to_registry:
    strategy:

      # We need to do a separate run for making each container
      # because the GH runners run out of memory very quickly
      matrix:
        platform: [arm64, i386 ] # linux/amd64, 
        include:
          # - platform: linux/amd64
          #   os: ubuntu-latest
          - platform: i386
            os: ubuntu-latest
          - platform: arm64
            os: macos-latest

    name: Push Docker image to Docker Hub
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # Taken from GitHub issue response:
      # https://github.com/actions/runner-images/issues/17#issuecomment-1537238473
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          
          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock


      # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ashtontm/test
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:/devenv/electrs/docker"
          file: ./Dockerfile
          push: true
          tags: ashtontm/test:latest-${{ matrix.platform }},ashtontm/test:1.0.0-${{ matrix.platform }}
          # platforms: linux/amd64,linux/arm64
          platforms: linux/${{ matrix.platform }}

          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}