
name: Publish Docker image

on:
  push:
    branches:
      - main
      - releases/** # From a cool demo.
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4


      # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ashtontm/test
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./devenv/electrs
          file: ./Dockerfile
          push: true
          tags: ashtontm/test:latest,ashtontm/test:1.0.0
          platforms: linux/amd64,linux/arm64

          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}